import {
  Activity,
  Bell,
  ChevronDown,
  ChevronRight,
  Database,
  Download,
  FileCode2,
  FileBarChart,
  GitCommit,
  HardDriveDownload,
  KeyRound,
  ListTree,
  LogIn,
  Menu,
  Moon,
  Package,
  Plus,
  Save,
  Search,
  Server,
  Settings,
  ShieldCheck,
  Sun,
  Table,
  Table2,
  Terminal,
  Users,
  X,
  type LucideIcon,
} from "lucide-react";
import type { PanoIkonAdi } from "../../data/turler";

/** Veri katmanındaki string ikon adlarını lucide bileşenlerine eşler. */
export const IKON_HARITASI: Record<PanoIkonAdi, LucideIcon> = {
  database: Database,
  table: Table,
  table2: Table2,
  activity: Activity,
  server: Server,
  "git-commit": GitCommit,
  "file-code": FileCode2,
  package: Package,
  terminal: Terminal,
  backup: HardDriveDownload,
  login: LogIn,
  index: ListTree,
  plus: Plus,
  download: Download,
  save: Save,
  report: FileBarChart,
};

export {
  Bell,
  ChevronDown,
  ChevronRight,
  Database,
  HardDriveDownload,
  KeyRound,
  ListTree,
  Menu,
  Moon,
  Search,
  Server,
  Settings,
  ShieldCheck,
  Sun,
  Table2,
  Terminal,
  Users,
  X,
  FileBarChart,
  Activity,
  LogIn,
};
export type { LucideIcon };
